apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: n8n
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: 'auto-instrumentation-inject'
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown 1000:1000 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: n8n-pvc
              mountPath: /data
      automountServiceAccountToken: false
      containers:
        - command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n start
          image: n8nio/n8n:latest
          imagePullPolicy: Always
          name: n8n
          ports:
            - containerPort: 5678
          env:
            - name: WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: n8n-configmap
                  key: WEBHOOK_URL
            - name: N8N_HOST
              valueFrom:
                configMapKeyRef:
                  name: n8n-configmap
                  key: N8N_HOST
            - name: DB_POSTGRESDB_HOST
              valueFrom:
                configMapKeyRef:
                  name: n8n-configmap
                  key: DB_POSTGRESDB_HOST
            - name: DB_POSTGRESDB_PORT
              valueFrom:
                configMapKeyRef:
                  name: n8n-configmap
                  key: DB_POSTGRESDB_PORT
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name: DB_TYPE
              value: postgresdb
            - name: N8N_PROXY_HOPS
              value: '1'
            - name: GENERIC_TIMEZONE
              value: America/Fortaleza
            - name: TZ
              value: America/Fortaleza
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: N8N_PROTOCOL
              value: http
            - name: N8N_PORT
              value: "5678"
          resources:
            requests:
              memory: "400Mi"
              cpu: "250m"
            limits:
              memory: "800Mi"
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-pvc
      restartPolicy: Always
      volumes:
        - name: n8n-pvc
          persistentVolumeClaim:
            claimName: n8n-pvc
        - name: n8n-secret
          secret:
            secretName: n8n-secret
