{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: n8n-postgres-secret
  namespace: n8n
data:
  {{- if eq .Values.configmap.env "prd" }}
  DB_POSTGRESDB_PASSWORD: 
  DB_POSTGRESDB_USER: 
  {{- else }}
  DB_POSTGRESDB_PASSWORD: 
  DB_POSTGRESDB_USER: 
  {{- end }}
{{- end }}