apiVersion: v1
name: n8n
description: Plaftaforma de lowcode n8n
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa1SdZTcudkyIf37-JlI3eME1Xiv_NRqYlPX1FwP8&s
keywords:
  - N8N
#Desenvolvedor Responsável
maintainers:
  - name: Arquitetura
